version: '3.8'

volumes:
  db-init:
  db-data:

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker_files/go/Dockerfile
    container_name: go-playground
    volumes:
      - './src:/go/src'
    ports:
      - '8444:8444'
    tty: true
    stdin_open: true
    networks:
      - default
  db:
    build:
      context: ./
      dockerfile: ./docker_files/mysql/Dockerfile
    container_name: go-playground-db
    restart: on-failure:5
    ports:
      - '3450:3306'
    environment:
      # 今回は勉強用のためセキュリティ無視で直書き
      MYSQL_ROOT_PASSWORD: 'root'
    tty: true
    volumes:
      - db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    networks:
      - default