version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker_files/go/Dockerfile
    container_name: go-playground
    volumes:
      - './src:/go/app/src'
    ports:
      - '8444:8444'
    tty: true
    stdin_open: true
