// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Grade struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewUser struct {
	Name         string `json:"name"`
	Age          int    `json:"age"`
	EmailAddress string `json:"emailAddress"`
	GradeID      string `json:"gradeId"`
}

type User struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Age          int    `json:"age"`
	EmailAddress string `json:"emailAddress"`
	Grade        *Grade `json:"grade"`
}
