package rule

const (
	// NotFound ...
	NotFound = 100
	// BadRequest ...
	BadRequest = 200
	// ShortBalance ...
	ShortBalance = 300
	// InternalServerError ...
	InternalServerError = 400
	// FailedToUpdate ...
	FailedToUpdate = 500
)
